### ISSUE TITLE
Shader error in 'd4rkpl4y3r/Optimizer/M00_001_01_Bottoms_01_CLOTH ACLS_Toon_AlphaCutout_Dither': undeclared identifier 'cov' at line 13100 (on d3d11)

### ISSUE THREAD

**Issue by Miiikro** [d4rkc0d3r/d4rkAvatarOptimizer#10]
I changed shader to ACiiL, even before I clicked ''Create Optimized Copy'' and it still turnes pink and the console errors:
Shader error in 'd4rkpl4y3r/Optimizer/M00_001_01_Bottoms_01_CLOTH ACLS_Toon_AlphaCutout_Dither': undeclared identifier 'cov' at line 13100 (on d3d11)
![Unity vrc optimizer issue](https://user-images.githubusercontent.com/111545227/188288684-2ec5ccec-9522-45a6-83a6-ac9e817f56af.PNG)

**Comment by Miiikro** [comment]
Please d4rkpl4y3r reply and fix it when online!, but what's the purpose of .unitypackage file?

**Comment by d4rkc0d3r** [comment]
I was able to reproduce the issue with ACLS AlphaCutoutDither shader and fixed it. It was caused by the extra coverage output paramter not getting declared in the fragment shader function declaration.  
Get the fix from here: https://github.com/d4rkc0d3r/d4rkAvatarOptimizer/archive/refs/heads/main.zip

**Comment by Miiikro** [comment]
I deleted this optimized copy and re-created another optimized copy, but it made it worse, it made everything pink and when I change some of the materials to another shader, some remain pink and never change, I closed the project without saving and re-opened the project, but all the issues never left even though I clicked don't save when closing it, but it's alright as long as the original copy is still there, but it's invisible, why is the original model invisible?
![Issue 3](https://user-images.githubusercontent.com/111545227/188969435-43e06559-3a17-46f1-8abc-1affd67f71ca.PNG)

**Comment by Miiikro** [comment]
> I was able to reproduce the issue with ACLS AlphaCutoutDither shader and fixed it. It was caused by the extra coverage output paramter not getting declared in the fragment shader function declaration. Get the fix from here: https://github.com/d4rkc0d3r/d4rkAvatarOptimizer/archive/refs/heads/main.zip

Yeah, but how to find the unitypackage itself?

**Comment by d4rkc0d3r** [comment]
You delete the old version of the optimizer from your unity project.  
Then you unpack the .zip and drag the unpacked folder into the assets folder of your unity project.  
After that you have the newest version of the optimizer installed. With that you can create a new optimized copy and it should work now.

**Comment by Miiikro** [comment]
> You delete the old version of the optimizer from your unity project. Then you unpack the .zip and drag the unpacked folder into the assets folder of your unity project. After that you have the newest version of the optimizer installed. With that you can create a new optimized copy and it should work now.

Thanks

**Comment by Miiikro** [comment]
can't find my issue Shader error in 'd4rkpl4y3r/Optimizer/M00_001_01_Bottoms_01_CLOTH ACLS_Toon_AlphaCutout_Dither': undeclared identifier 'cov' at line 13100 (on d3d11) #10 in the d4rkpl4y3r/Optimizer issue tracker, the only issue there was https://github.com/d4rkc0d3r/d4rkAvatarOptimizer/issues/9, does Git hate me that much!!
