### ISSUE TITLE
d4rk crashes if the avatar descriptor is set to the default fx controller

### ISSUE THREAD

**Issue by SenkyDragon** [d4rkc0d3r/d4rkAvatarOptimizer#101]

**Comment by SenkyDragon** [comment]
The console is also flooded with errors when the editor is focused.

**Comment by d4rkc0d3r** [comment]
What exactly do you mean by set to default fx controller? Just removing the custom one with the x button? In that case I tried that and could not reproduce this crash.

**Comment by SenkyDragon** [comment]
I think this was related to https://github.com/d4rkc0d3r/d4rkAvatarOptimizer/issues/100 when vrcfury was used with no layer-creating features, since vrcf was inserting an empty fx controller and then d4rk was removing the base layer.
