### ISSUE TITLE
Recursive shader includes does not expand paths properly

### ISSUE THREAD

**Issue by hyblocker** [d4rkc0d3r/d4rkAvatarOptimizer#106]
The recursive shader include parser fails to correctly resolve the following types of paths:

```c
// Common files
#include "/Assets/Hekky/Shaders/Common/Sampling.cginc"
#include "/Assets/Hekky/Shaders/Common/VRCMisc.cginc"
#include "/Assets/Hekky/Shaders/Common/AudioLinkHelpers.cginc"
#include "/Assets/Hekky/Shaders/Common/UnityUtils.cginc"
#include "/Assets/Hekky/Shaders/Common/Lighting.cginc"
#include "/Assets/Hekky/Shaders/Common/Blending.cginc"
```

These paths use a `/` to tell the shader compiler to start looking at the project root, so that no matter where I use the above lines from within a project, it will always find the absolute path.

**Comment by d4rkc0d3r** [comment]
Try to remove the leading `/`.
Weird that it doesn't work though as I remember specifically adding support for that
https://github.com/d4rkc0d3r/d4rkAvatarOptimizer/blob/main/Editor/ShaderAnalyzer.cs#L382

**Comment by hyblocker** [comment]
I had to change it to this to get it to work:
```cs
if (currentFilePath.StartsWithSimple("/Assets/") || currentFilePath.StartsWithSimple("Assets/"))
{
    var path = Path.GetDirectoryName(callerPath);
    var assetFolderPath = path.IndexOf("Assets") != -1 ? path.Substring(0, path.IndexOf("Assets") - 1) : path;
    if (currentFilePath[0] == '/') {
        currentFilePath = currentFilePath.Substring(1);
    }
    currentFilePath = Path.Combine(assetFolderPath, currentFilePath);
}
```

I think it's because of the leading `/` causing `Path.Combine` to mess up the evaluated path.
