### ISSUE TITLE
Constant curve motion time anim is smoothed out when using Combine MT Approx

### ISSUE THREAD

**Issue by ScruffyRules** [d4rkc0d3r/d4rkAvatarOptimizer#108]
![image](https://github.com/d4rkc0d3r/d4rkAvatarOptimizer/assets/5356779/72dcc9cb-46c0-427c-868d-64e53691f940)
I know it's approximation but it destroyed my constant curve!

**Comment by d4rkc0d3r** [comment]
Make the new global setting a big number and it should better approximate this curve.
