### ISSUE TITLE
I changed material to the supported shader Vrchat/Mobile/Toon Lit and this happened

### ISSUE THREAD

**Issue by Miiikro** [d4rkc0d3r/d4rkAvatarOptimizer#11]
![Used Vrchat Mobile Toon Lit and this happened](https://user-images.githubusercontent.com/111545227/189514221-2b1fa4ac-aaa4-48cd-bff8-845b38fe662e.PNG)

**Comment by Miiikro** [comment]
Idk what happened to my first issue I first submitted  https://github.com/d4rkc0d3r/d4rkAvatarOptimizer/issues/10, how the heck was it removed from the issue tracker?

**Comment by Miiikro** [comment]
Idk why when I clicked create optimized copy with supported the shader Toon Lit , it automatically changed to d4rkpl4y3r/Optimizer ACLS_Toon_AlphaCutout_Dither, which isn't the correct and supported shader, and when I changed it to the supported shader, it turned my shader white, and it did change the material slots to 9 -> 5, before I changed it, it was originally 16 -> 9, and clicked optimize copy became 9 -> 9 before I changed it to Toon Lit

**Comment by d4rkc0d3r** [comment]
Are you trying to make a custom avatar for quest? If so this tool is not for that. It requires support for custom shaders to work which VRChat does not allow on quest.

**Comment by J-E-Mc** [comment]
I use this tool for quest simply to remove unused blendshapes and to use ring finger as foot collider, but this tool does modify the shaders, you can fix this by just replacing the materials with their originals after the optimiser is finished (make sure to disable all of the merge-mesh and merge-materials settings though, as they will not work on quest)

**Comment by jerryzmtz** [comment]
> I use this tool for quest simply to remove unused blendshapes and to use ring finger as foot collider, but this tool does modify the shaders, you can fix this by just replacing the materials with their originals after the optimiser is finished (make sure to disable all of the merge-mesh and merge-materials settings though, as they will not work on quest)

I have the same concern. It would be great if there is a quest option.

**Comment by d4rkc0d3r** [comment]
v3.0.0 has support for reduced optimizations on quest / android now.
