### ISSUE TITLE
Feature Request: Improved Exclusion Mechanism for Prefab Variants with d4rk Optimizer

### ISSUE THREAD

**Issue by jerryzmtz** [d4rkc0d3r/d4rkAvatarOptimizer#112]
Current Issue:

I use prefabs to create variants with one avatar base. The original prefab includes the d4rk optimizer as part of it. However, I encounter an issue when I want to exclude a specific game object from the d4rk optimizer. To achieve this, I currently have to unpack the prefab, which is not ideal. When the prefab is intact, the d4rk optimizer always reverts to the original state defined in the prefab.

For instance, if I exclude "Test Object" from the avatar "VF_Test_Soraha Variant," it initially appears to work. However, after changing scenes and returning, the exclusion is lost, and the optimizer reverts to the original configuration where nothing is excluded.

Proposed Improvement:

I propose enhancing the d4rk optimizer to allow exclusions based on shader name or object name. This way, even if the prefab is intact and cannot be directly edited, the exclusions would persist. Or maybe it could be improved to something like modular avatar, where you could edit certain component even if it is prefabed.

![image](https://github.com/user-attachments/assets/ce7623e1-7272-47bb-8c68-ccc055b624c5)
![image](https://github.com/user-attachments/assets/b51301f4-88ea-4c69-9562-3ead444d4070)

**Comment by d4rkc0d3r** [comment]
3.8.0 should now support exclusions with prefab variants properly.
