### ISSUE TITLE
[Feature Request] Head Collider

### ISSUE THREAD

**Issue by Reava** [d4rkc0d3r/d4rkAvatarOptimizer#113]
A toggle to move one of the finger's colliders to the head, the same way it is done with the feet ones, take the left distal or some similar bone collider, this way both hands, feet and head can interact.

that'd be pretty great ^^ sorry for the scuffed issue wording, there's really nothing fancy or structured to say
thanks for your work!

**Comment by d4rkc0d3r** [comment]
The feet collider are already out of scope for an optimizer. I won't go any further in that direction.
If you want to do something like this try [VRCFury global colliders](https://vrcfury.com/components/global-collider) instead.
