### ISSUE TITLE
"Delete Unused Gameobject" doesn't play well with FinalIK

### ISSUE THREAD

**Issue by kyrahabattoir** [d4rkc0d3r/d4rkAvatarOptimizer#115]
If you use gameobjects in a FinalIK bone chain they end up optimized away.

Would it be possible to make the optimizer aware of FinalIK components?

**Comment by d4rkc0d3r** [comment]
It will probably be fixed when I switch to a more generic version of finding referenced transforms. I have that planned for adding support for the VRC constraints.
Hopefully that will then also just work with FinalIK then. I'll write another message here whenever I have implemented that.

**Comment by d4rkc0d3r** [comment]
3.8.0 should now work with FinalIK components.
However my testing was only very minimal so there might still be some bugs. If you find any please just make a new issue with steps to reproduce.
