### ISSUE TITLE
Shader optimizations don't work on material variants

### ISSUE THREAD

**Issue by lackofbindings** [d4rkc0d3r/d4rkAvatarOptimizer#116]
If any material variants are used on the avatar, shader optimizations appear to fail with "Attempted to set shader on material variant". The build appears to continue as normal but without shader optimizations. My use case involves having material variants and then having the optimizer write the static values. This could likely be remedied by having the optimizer make copies of the material variants and then flatten them (see: top left three dots menu > flatten material variant) before continuing with other steps.

**Comment by d4rkc0d3r** [comment]
3.8.0 should now work with material variants.
