### ISSUE TITLE
Merge different property materials not in menu

### ISSUE THREAD

**Issue by SamMod1** [d4rkc0d3r/d4rkAvatarOptimizer#117]
Hi, apologies if this isn't an issue but I haven't been able to figure out why the "Merge different property materials" option isn't showing for me.

My avi has three materials, and I can't see or select the merge materials option. Furthermore when selecting the basic or full options (which as I understand should merge mateirals) the materials don't merge. None of my materials show up in the "Unmergable materials" list. What could be causing my problem?

I'm using 2022.3.22f1 and used the "https://d4rkc0d3r.github.io/vpm-repos/main.json" when adding the repo in creator companion as instructed. It's installed version 3.7.4.

Thank you.
![issue 1](https://github.com/user-attachments/assets/167a33db-a6d0-4026-add8-ccdb3d48798f)
![issue 2](https://github.com/user-attachments/assets/080a2a59-7539-47c8-8990-b678e65d90f9)

**Comment by d4rkc0d3r** [comment]
The options that are not shown to you are only for PC avatars. They are hidden with other build targets as custom shaders aren't supported on other platforms.
On those platforms you can only use the basic merge which will merge material slots that use the same materials. You can see in the preview that it merges the `Wings` mesh into the `Body` mesh and merges the appropriate material slots that both have the `Misc` material in them.

**Comment by SamMod1** [comment]
Oh, thank you. I was hoping to use your optimizer to create a fallback version of the quest version of my avatar. Will this not be possible then without re-creating all of the textures based on one material from the beginning?
