### ISSUE TITLE
`Normalized Blend Values` ​​option is always disabled for Direct Blend Tree

### ISSUE THREAD

**Issue by noridev** [d4rkc0d3r/d4rkAvatarOptimizer#120]
Hello. I am using an asset that moves the breast in the [booth](https://booth.pm/ja/items/5453882).
This asset uses the `Normalized Blend Values` feature of Direct Blend Tree, and when I apply d4rkAvatarOptimizer to the avatar, the Normalized Blend Values ​​setting is turned off, causing problems.

The AvatarOptimizer made by anatawa12's previously had the same problem, and it was caused by making it without considering Normalized Weights.
[Related Content](https://x.com/anatawa12_vrc/status/1801938956734599234)

Can you please check if the avatar is optimized according to the Normalized Blend Values ​​option status for Direct Blend Tree?

**Constraints**
- The avatar was downloaded from the booth and no modifications were made to it.
- The only new component added to the avatar was d4rkAvatarOptimizer.
- There were no issues when using Anatawa12's Avatar Optimizer with VRCFury, add d4rkAvatarOptimizer, the issue occurs.

This is the FX layer in Play Mode. You can see that Normalized Blend Values is turned off.
![image](https://github.com/user-attachments/assets/62b0f3e8-e916-454e-ab9e-b0684537f684)   

Since the issue persists even with all options disabled, it seems like the underlying processing is causing the issue.
![image](https://github.com/user-attachments/assets/02416d20-66aa-489b-a340-d9b9ab69ad95)

**Comment by d4rkc0d3r** [comment]
Seems like `Normalized Blend Values` doesn't exist in the BlendTree api so I'll have to copy that property with serialized object instead. thanks unity
