### ISSUE TITLE
Enabling the `Optimize FX Layer` feature removes the Layer 0 of the FX Layer.

### ISSUE THREAD

**Issue by noridev** [d4rkc0d3r/d4rkAvatarOptimizer#122]
In the case of MMD world, Left Hand(Layer 1) and Right Hand(Layer 2) are disabled in order from the top to prevent expressions from being mixed by the controller.
However, if you use the `Optimize FX Layer` function, the empty layer at the top of the FX layer is removed.

Judging from the fact that it is removed even when other animations are added, I think it is set to remove Layer 0 unconditionally.(maybe)

In general situations, there is no problem, but in certain worlds like MMD, I think manipulation according to the layer order can have an impact.

When testing, if you dance in the MMD world with an avatar with Layer 0 removed, the Weight of Left Hand(originally Layer 1) is not set to 0 in the debug window, but the Right Hand(originally Layer 2) and the layers below it are set to Weight 0.

It may be better to not remove Layer 0 at all, or to add a toggle such as MMD compatibility and it so that Layer 0 is not removed when checked.

**Comment by Toys0125** [comment]
I want to comment as a workaround: having a valid animation like a reset animation in the base layer will prevent this, or using VRCFury, which puts a valid animation inside the base layer.

**Comment by d4rkc0d3r** [comment]
So if I read this right, I need to not touch (no merging, no deleting) the first 3 layers in FX for MMD compatibility?

If so I'll just add that to `Keep MMD Blend Shapes` and rename it to `MMD Compatibility`

**Comment by noridev** [comment]
That would be better.
Since Left Hand / Right Hand have `VRC Animator Tracking Control`, it is highly likely that they will not be merged anyway.

Therefore, it seems better not to merge or delete layers 0, 1, and 2 of the FX layer.

However, since there are definitely users who do not visit the MMD world and have a large number of layers, and want to reduce the number of layers by one to improve performance, I would like to suggest that rather than integrating with the `Keep MMD Blend Shapes` option, enable the `MMD compatibility` option to allow two settings to be selected.

**Comment by d4rkc0d3r** [comment]
What use case is there to keeping MMD blendshapes when not going to MMD worlds?
In general I don't like to have too many options and to me it seems you either wan MMD compatibility or not.
