### ISSUE TITLE
Problems with bounds size 

### ISSUE THREAD

**Issue by gutierrezvalentino** [d4rkc0d3r/d4rkAvatarOptimizer#127]
Hi, im having a problem with the bounds size, when using the merge skinned meshes, it causes the bounds to go from 2.36 / 2.75 / 2.36 to ~ 11 / 12 / 11 
This is the bounds without the merge skinned meshes toggle.
![image](https://github.com/user-attachments/assets/dc97efdc-8acf-4bc2-9840-27db8ec70913)

That is causing the avatar to get very poor rating, is there a way to fix this? thanks!

**Comment by d4rkc0d3r** [comment]
This can happen when you have meshes or bones that are smaller than scale 1 and have an animation to scale them. When merging the meshes it first sets the scale of such bones to 1 before merging the meshes to ensure nothing breaks. (Baking meshes that are very scaled down destroys them and this behavior is to fix that.)

At the very least the very poor rating from bounds is purely visual. If bounds is the only thing above the limit then your avatar will not get performance blocked by the avatar rank limit in the menu.
