### ISSUE TITLE
[BUG] "The VRCSDK build was aborted because the VRCSDKPreprocessAvatarCallback 'AvatarBuildHook' reported a failure."

### ISSUE THREAD

**Issue by Rycia** [d4rkc0d3r/d4rkAvatarOptimizer#129]
I came across this error when building for quest and for the life of me I can't figure out what it is.

![image](https://github.com/user-attachments/assets/74112bf4-e58b-4a25-a38b-d30b0c420088)
![image](https://github.com/user-attachments/assets/81a49a7e-2c83-4e2c-b5db-38622dd85132)
![image](https://github.com/user-attachments/assets/9d480ac0-e80d-4fcc-9359-30c524efa24d)
![image](https://github.com/user-attachments/assets/0e7c0e16-01e3-480b-8c00-462ffdbbeac0)
![image](https://github.com/user-attachments/assets/cf3b4e3d-5952-4726-bd06-378a221a1d84)
![image](https://github.com/user-attachments/assets/b14cbb60-77dc-4a6d-811b-1037b9cb2c47)
![image](https://github.com/user-attachments/assets/66827536-531e-43be-b4b7-c99b7b99000e)

```
System.IndexOutOfRangeException: Index was outside the bounds of the array.
  at d4rkAvatarOptimizer.FindAllPhysBoneDependencies () [0x0033f] in .\Packages\d4rkpl4y3r.d4rkavataroptimizer\Editor\d4rkAvatarOptimizer.cs:2251 
  at d4rkAvatarOptimizer.FindAllPhysBonesToDisable () [0x00010] in .\Packages\d4rkpl4y3r.d4rkavataroptimizer\Editor\d4rkAvatarOptimizer.cs:2308 
  at d4rkAvatarOptimizer.Optimize () [0x0014c] in .\Packages\d4rkpl4y3r.d4rkavataroptimizer\Editor\d4rkAvatarOptimizer.cs:155 
  at d4rkpl4y3r.AvatarOptimizer.AvatarBuildHook.OnPreprocessAvatar (UnityEngine.GameObject avatarGameObject) [0x00045] in .\Packages\d4rkpl4y3r.d4rkavataroptimizer\Editor\AvatarBuildHook.cs:37 
UnityEngine.Logger:Log (UnityEngine.LogType,object)
(wrapper dynamic-method) UnityEngine.Debug:UnityEngine.Debug.LogError_Patch1 (object)
d4rkpl4y3r.AvatarOptimizer.AvatarBuildHook:OnPreprocessAvatar (UnityEngine.GameObject) (at ./Packages/d4rkpl4y3r.d4rkavataroptimizer/Editor/AvatarBuildHook.cs:42)
VRC.SDKBase.Editor.BuildPipeline.VRCBuildPipelineCallbacks:OnPreprocessAvatar (UnityEngine.GameObject)
nadena.dev.ndmf.ApplyOnPlay:MaybeProcessAvatar (nadena.dev.ndmf.runtime.ApplyOnPlayGlobalActivator/OnDemandSource,UnityEngine.MonoBehaviour) (at ./Packages/nadena.dev.ndmf/Editor/ApplyOnPlay.cs:98)
nadena.dev.ndmf.runtime.AvatarActivator:Awake () (at ./Packages/nadena.dev.ndmf/Runtime/ApplyOnPlayGlobalActivator.cs:187)
UnityEngine.GameObject:AddComponent<nadena.dev.ndmf.runtime.AvatarActivator> ()
nadena.dev.ndmf.runtime.RuntimeUtil:GetOrAddComponent<nadena.dev.ndmf.runtime.AvatarActivator> (UnityEngine.GameObject) (at ./Packages/nadena.dev.ndmf/Runtime/RuntimeUtil.cs:33)
nadena.dev.ndmf.runtime.ApplyOnPlayGlobalActivator:Awake () (at ./Packages/nadena.dev.ndmf/Runtime/ApplyOnPlayGlobalActivator.cs:125)
```

```
The VRCSDK build was aborted because the VRCSDKPreprocessAvatarCallback 'AvatarBuildHook' reported a failure.
UnityEngine.Logger:Log (UnityEngine.LogType,object)
(wrapper dynamic-method) UnityEngine.Debug:UnityEngine.Debug.LogError_Patch1 (object)
VRC.SDKBase.Editor.BuildPipeline.VRCBuildPipelineCallbacks:OnPreprocessAvatar (UnityEngine.GameObject)
nadena.dev.ndmf.ApplyOnPlay:MaybeProcessAvatar (nadena.dev.ndmf.runtime.ApplyOnPlayGlobalActivator/OnDemandSource,UnityEngine.MonoBehaviour) (at ./Packages/nadena.dev.ndmf/Editor/ApplyOnPlay.cs:98)
nadena.dev.ndmf.runtime.AvatarActivator:Awake () (at ./Packages/nadena.dev.ndmf/Runtime/ApplyOnPlayGlobalActivator.cs:187)
UnityEngine.GameObject:AddComponent<nadena.dev.ndmf.runtime.AvatarActivator> ()
nadena.dev.ndmf.runtime.RuntimeUtil:GetOrAddComponent<nadena.dev.ndmf.runtime.AvatarActivator> (UnityEngine.GameObject) (at ./Packages/nadena.dev.ndmf/Runtime/RuntimeUtil.cs:33)
nadena.dev.ndmf.runtime.ApplyOnPlayGlobalActivator:Awake () (at ./Packages/nadena.dev.ndmf/Runtime/ApplyOnPlayGlobalActivator.cs:125)
```

Also getting this after saving the avatar prefab after trying to turn off delete unused objects (with no different of a result.)
![{19FB8C45-367E-4F90-82EF-ED2B3C8604A0}](https://github.com/user-attachments/assets/53ce7a7a-3280-4ffc-af3c-9611868b124a)

Also confirmed my avatar works fine when I remove the d4rk optimizer component completely.
Also fails when the component is added with none of the options except apply on upload is on;
![{4069A4DD-E1C5-4010-8BA5-4B6A88FC3393}](https://github.com/user-attachments/assets/e6e856ac-7839-4af1-b98a-b029f7f1c880)

**Comment by d4rkc0d3r** [comment]
Uh oh. That error means you have a skinned mesh that does something really weird. It has at least one vertex that references a bone id that is larger than the list of bones in the skinned mesh renderer. That should not be a thing a mesh has.

Shouldn't be hard for me to log some warnings instead of producing an error though.

**Comment by Rycia** [comment]
If you could log _which_ skinned mesh has the issue, that'd be super helpful too.

**Comment by d4rkc0d3r** [comment]
This should now be a warning instead of a crash in 3.9.1

**Comment by d4rkc0d3r** [comment]
@vrcnunu 
Nothing in this error message points at my tool so this is definitely the wrong place. The thing that fails is `AssignAvatarNetworkIDs` so I assume that is some vrchat sdk thingy. Good luck with your trouble shooting, but you won't find help for that here.
