### ISSUE TITLE
Limit triangle count for optimized/output skinned meshes with shapekeys

### ISSUE THREAD

**Issue by Asovrix** [d4rkc0d3r/d4rkAvatarOptimizer#13]
As in title. Merging skinned meshes is good as long as you don't end up with high-poly ones with shapekeys on them.

**Comment by d4rkc0d3r** [comment]
By default the optimizer doesn't merge meshes that use shape keys with ones that don't.
There is an option to merge regardless which is useful for small avatars, but its off by default.
