### ISSUE TITLE
Objects behave very badly when SPS is activated!

### ISSUE THREAD

**Issue by QueenOfFrance** [d4rkc0d3r/d4rkAvatarOptimizer#131]
(Seen on discord!) 
-> An object comes into contact with the SPS, the mesh becomes disfigured (or something like that, not much explanation :/)

(Modified on 10/21/2024 at 04:40 French time: This bug has been occurring since the new update, previously this did not happen!)

**Comment by d4rkc0d3r** [comment]
3.9.3 should now automatically detect and exclude SPS penetrators from optimizations
