### ISSUE TITLE
Animations affecting transforms of objects that have had their parents removed are not updated properly

### ISSUE THREAD

**Issue by J-E-Mc** [d4rkc0d3r/d4rkAvatarOptimizer#14]
This issue occurs on the nardoragon base and probably others, but this is the only one I've seen doing this so far
![image](https://user-images.githubusercontent.com/44543806/196527422-18ad0c43-5d97-4133-8211-78161df32e34.png)
there is a bone named "TailRoot" that is never moved from it's original position contains another object named "Tail1" which is moved.

there is a set of animations which rotate Tail1 but the avatar optimiser removes TailRoot so the animations that effect Tail1 have a significant offset since TailRoot had an X rotation of -85.743, which the optimiser correctly applies to Tail1, but not to the animations that affect it

Tail1 rotation pre-optimisation is X -24.335, post-optimisation is X -110.079, but the idle animation resets it to -24.335 causing this issue to occur (the tail is too high)
![image](https://user-images.githubusercontent.com/44543806/196528273-6b3ac2cc-5494-4762-a2c5-00f79c4e7b66.png)
it should look like this:
![image](https://user-images.githubusercontent.com/44543806/196528363-eac8bc99-3488-4784-98d2-22a2ab446dc0.png)

**Comment by d4rkc0d3r** [comment]
You can disable the "Delete Unused Game Objects" option to have it not delete them as a workaround.

For a fix it seems like I have to keep the parents of transforms that get animated too.

**Comment by d4rkc0d3r** [comment]
This is fixed for the next version. You can download the main branch from [here](https://github.com/d4rkc0d3r/d4rkAvatarOptimizer/archive/refs/heads/main.zip) to get it right now.
