### ISSUE TITLE
Having skinned mesh/mesh components disabled can produce incorrect results in optimized copy

### ISSUE THREAD

**Issue by Asovrix** [d4rkc0d3r/d4rkAvatarOptimizer#15]
As in title.
Apparently toggling skinned mesh/mesh components is way more performant than toggling the entire gameobject with mesh on it.
It seems though that optimizer does not seem to properly support these kind of scenarios and produces a copy where meshes are not getting enabled/disabled the same way as on input avatar.
To reproduce try to switch your gameobject toggles into skinned mesh component toggles in hierarchy and in animations, aka you toggle lower checkbox instead of upper one:
![Unity_2022-11-03_15-29-04](https://user-images.githubusercontent.com/44006686/199748524-70ecab9a-d630-40e2-a629-996b8a09e6b1.png)

**Comment by Asovrix** [comment]
Problem seems to occur when a gameobject where (skinned) mesh renderer is enabled gets merged to a different gameobject where renderer is disabled. Result of it is that on optimized copy that merged mesh which was disabled stays disabled and toggling it on manually doesn't yield proper results when it comes to animating parts of it on or off.

**Comment by d4rkc0d3r** [comment]
I fixed the SkinnedMeshRenderer component being disabled when other stuff get merged into it. I also changed how I save the optimized materials. Would be nice to know if that fixes it. You can get the newest version right [here](https://github.com/d4rkc0d3r/d4rkAvatarOptimizer/archive/refs/heads/main.zip).

> Apparently toggling skinned mesh/mesh components is way more performant than toggling the entire gameobject with mesh on it.

Yes technically it is. However if you use the optimizer you won't have either of those toggles left over so it doesn't matter in this case. Also unless you toggle your meshes rapidly this is also a non issue.
