### ISSUE TITLE
Shader doesn't fallback nicely - albedo texture isn't shown when custom shaders are disabled in-game

### ISSUE THREAD

**Issue by Asovrix** [d4rkc0d3r/d4rkAvatarOptimizer#17]
As in topic. Issue only appears on meshes which end up having part toggles added by this shader, even though original one (ACLS in this case) should fall back more nicely.
![Unity_2022-11-22_04-51-26](https://user-images.githubusercontent.com/44006686/203217097-1050ace0-dc68-4b6f-b104-b30513749d90.png)
![VRChat_2022-10-22_22-30-37 039_1920x1080](https://user-images.githubusercontent.com/44006686/203217351-7528bac4-b0bd-4414-bf5a-c3b2a11e4173.png)

**Comment by d4rkc0d3r** [comment]
It should only happen if the _MainTexture is not already an atlas and gets put into a Texture2DArray. Can you check if it really is just from merged toggles? (Also merged shader toggles fall back to show everything as on when shaders a blocked, another limitation)

**Comment by Asovrix** [comment]
Yeah, I am aware of everything defaulting to be shown with only shaders being hidden.
MainTex on body parts that are solid white on above photo are all indeed using 2DArray textures, it doesn't seem to be related to toggles, especially only now I realized that my shoes are fine even though they are toggleable.

**Comment by d4rkc0d3r** [comment]
Hmm maybe I should write those limitations down in the README. I could even add an info box that only shows up when it merges different _MainTex textures into an array.

**Comment by d4rkc0d3r** [comment]
3.3.0 now has merging of _MainTex as a separate option that is off by default.
