### ISSUE TITLE
Shader error on an optimized material using ACLS Toon Solid Outline 2.11.1

### ISSUE THREAD

**Issue by Asovrix** [d4rkc0d3r/d4rkAvatarOptimizer#20]
Unfortunately Github actively refuses to take ZIP file of the Unitypackage with shader and material files, so I needed to host it on Google Drive: https://drive.google.com/file/d/1hvf7FsKcclYjUk7_USlLTG8edpRpYzU6/view?usp=share_link

> Shader error in 'd4rkpl4y3r/Optimizer/Bunny_Belt ACLS ACLS_Toon_Solid_Outline': '_MatCapTexMult_Wrapper::GetDimensions': no matching 4 parameter method at line 8834 (on d3d11)

**Comment by d4rkc0d3r** [comment]
This should fix it, however I didn't test it on my end. I was simply missing overloads of the `Texture2D.GetDimensions()`  methods in my wrapper class.  
Try the fix from [here](https://github.com/d4rkc0d3r/d4rkAvatarOptimizer/archive/refs/heads/main.zip).

**Comment by Asovrix** [comment]
Whoops... forgot about this.
Issue has been solved after using above fix.
