### ISSUE TITLE
ACLS shader, decal texture position doesn't match between normal and optimized material

### ISSUE THREAD

**Issue by Asovrix** [d4rkc0d3r/d4rkAvatarOptimizer#21]
As in title, changing values on optimized material doesn't seem to work either, so I can't fix it even if I would want to.
Before:
![Unity_2022-12-26_17-33-45](https://user-images.githubusercontent.com/44006686/209568316-482dd11c-6aff-494c-9142-331a07079c93.png)
![Unity_2022-12-26_17-33-58](https://user-images.githubusercontent.com/44006686/209568325-60958bf8-3604-4b0a-9f2c-f9c556af375c.png)
After:
![Unity_2022-12-26_17-37-08](https://user-images.githubusercontent.com/44006686/209568335-f5a01515-8767-4aed-8548-7dc19d3688f2.png)
![Unity_2022-12-26_17-37-19](https://user-images.githubusercontent.com/44006686/209568344-87501639-5204-4caf-b7f6-43624c30ff23.png)

Settings for optimizer:
![Unity_2022-12-26_17-40-08](https://user-images.githubusercontent.com/44006686/209568493-a90abb53-4743-433b-8af9-388c0fff3eca.png)

**Comment by Asovrix** [comment]
It seems like positions get rounded up/down to nearest 1/10 of a coordinate instead of being saved exactly?

**Comment by d4rkc0d3r** [comment]
Can you send me the optimized materials with its generated shader when its broken so I can take a look at them?

**Comment by Asovrix** [comment]
there it is https://drive.google.com/file/d/19_E4DR4Wjgpm-HWFTM-b6csVjZ91JwZO/view?usp=sharing
