### ISSUE TITLE
Object refrence not set to an instance of an object.

### ISSUE THREAD

**Issue by Shadowthynightwing** [d4rkc0d3r/d4rkAvatarOptimizer#22]
Unsure of what's actually causing this. Everything in terms of debug looks fine, but happens every time I go to create a copy.
![image](https://user-images.githubusercontent.com/122242437/211229799-b38e890b-efbb-4550-b59a-2c01dd14b70c.png)

**Comment by d4rkc0d3r** [comment]
Hmm if you use version 1.7 it looks like there is some renderer component that has no mesh: https://github.com/d4rkc0d3r/d4rkAvatarOptimizer/blob/5981f434eb0921ca6c0a9055d275fe77e8f97ec3/src/d4rkAvatarOptimizerEditor.cs#L1756
