### ISSUE TITLE
Release as UPM/VPM Package

### ISSUE THREAD

**Issue by TayouVR** [d4rkc0d3r/d4rkAvatarOptimizer#23]
would be nice to have, also later down the line maybe VRC could even have the package in the VCC, making quick and easy optimization more popular and accessible.

I personally would like to use the UPM, but the formats should be compatible either way. If you need help setting up a package manifest or the assembly definition I'd be happy to help, I could even PR this myself if you like.

**Comment by d4rkc0d3r** [comment]
Next version will be VPM compatible.
