### ISSUE TITLE
Texture compression analyzer - shouldn't DXT5 be called DXTnm instead for normal maps?

### ISSUE THREAD

**Issue by Asovrix** [d4rkc0d3r/d4rkAvatarOptimizer#25]
https://cdn.discordapp.com/attachments/923127683800518696/1065298692707463228/2023-01-18_16-56-26.png
I guess it would make sense especially since that format is more specialized version meant for normal maps, which still produces better quality than "High quality" BC7?

**Comment by d4rkc0d3r** [comment]
DXTnm isn't an actual TextureFormat. It's still just DXT5 or DXT5Crunched under the hood. The names in the analyzer are the property names of https://docs.unity3d.com/ScriptReference/TextureFormat.html

Also I can't believe that you actually had a normal map that scored better SSIM with DXT5 than with BC7, lol. All the ones I tested were always BC5 > BC7 > DXT5.

And subjectively DXT5 normal maps look horrible with large block artifacts which even BC7 doesn't suffer from.
