### ISSUE TITLE
Prevent MMD shapekeys being deleted

### ISSUE THREAD

**Issue by jerryzmtz** [d4rkc0d3r/d4rkAvatarOptimizer#32]
I think it will be good if MMD shapekeys could be kept after optimization.

**Comment by d4rkc0d3r** [comment]
If you can point me to a list of all MMD shapekeys I could add an option to keep them. A quick google search refused to give me any kind of list of MMD shapekey names.

**Comment by jerryzmtz** [comment]
You could get a full list here: https://www.deviantart.com/xoriu/art/MMD-Facial-Expressions-Chart-341504917

MMD shapekeys name will be something like "まばたき", "笑い" or "Blink", "Smile" or both of them

BLUE - EYES

まばたき - Blink
笑い - Smile
ウィンク - Wink
ウィンク右 - Wink-a
ウィンク２ - Wink-b
ｳｨﾝｸ２右 - Wink-c
なごみ - Howawa
はぅ - > <
びっくり - Ha!!!
じと目 - Jito-eye
ｷﾘｯ - Kiri-eye
はちゅ目 - O O
星目 - EyeStar
はぁと - EyeHeart
瞳小 - EyeSmall
瞳縦潰れ - EyeSmall-v
光下 - EyeUnderli
恐ろしい子！ - EyeFunky
ハイライト消 - EyeHi-off
映り込み消 - EyeRef-off
喜び - Joy
わぉ?! - Wao?!
なごみω - Howawa ω
悲しむ - Wail
敵意 - Hostility


PINK - MOUTH

あ - a
い - i
う - u
え - e
お - o
あ２ - a 2
ん - n
▲ - Mouse_1
∧ - Mouse_2
□ - □
ワ - Wa
ω - Omega
ω□ - ω□
にやり - Niyari
にやり２ - Niyari2
にっこり - Smile
ぺろっ - Pero
てへぺろ - Bero-tehe
てへぺろ２ - Bero-tehe2
口角上げ - MouseUP
口角下げ - MouseDW
口横広げ - MouseWD
歯無し上 - ToothAnon
歯無し下 - ToothBnon


GREEN - BROWS

真面目 - Serious
困る - Trouble
にこり - Smily
怒り - Get angry
上 - UP
下 - Down

**Comment by d4rkc0d3r** [comment]
Ok, so the option should keep both the JP and EN names, right?
Thanks for the list!

**Comment by jerryzmtz** [comment]
Yes, I think it would be great if both JP and EN blendshapekeys are kept. By the way, love your tool very much. It helps a lot.

**Comment by d4rkc0d3r** [comment]
This is now live in 2.1.0
