### ISSUE TITLE
Support surface shaders by using the output of "Show generated code"?

### ISSUE THREAD

**Issue by kitlith** [d4rkc0d3r/d4rkAvatarOptimizer#37]
screenshot of the relevant button at the top of a surface shader: 
![image](https://github.com/d4rkc0d3r/d4rkAvatarOptimizer/assets/7027737/e9311652-289f-4585-baa4-40e7de618ae9)

I was able to manually use the output of this button for the Furality Sylva shader, and have a merged mesh with working shaders in the end.

**Comment by kitlith** [comment]
Ah. I guess that doesn't work when trying to merge materials, for maybe the same reason the Standard shader doesn't work.

**Comment by d4rkc0d3r** [comment]
That isn't a nice exposed API, just some internal call that opens it in a text editor. I don't plan to support surface shaders in this way as its not really feasible.
