### ISSUE TITLE
Blend shape index out of range

### ISSUE THREAD

**Issue by jerryzmtz** [d4rkc0d3r/d4rkAvatarOptimizer#38]
My optimization failed because of the following problem:

```
ArgumentException: Blend shape index out of range.
d4rkAvatarOptimizer.CombineSkinnedMeshes () (at Packages/d4rkpl4y3r.d4rkavataroptimizer/Editor/d4rkAvatarOptimizer.cs:2765)
d4rkAvatarOptimizer.Optimize () (at Packages/d4rkpl4y3r.d4rkavataroptimizer/Editor/d4rkAvatarOptimizer.cs:95)
d4rkAvatarOptimizerEditor.OnInspectorGUI () (at Packages/d4rkpl4y3r.d4rkavataroptimizer/Editor/d4rkAvatarOptimizerEditor.cs:959)
UnityEditor.UIElements.InspectorElement+<>c__DisplayClass58_0.<CreateIMGUIInspectorFromEditor>b__0 () (at <a259d3c004024353a2c217da97495055>:0)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)
```

This could be fixed when I exclude the problematic skinned mesh, named body. It includes 286 Blend Shapes, is this a problem?

**Comment by d4rkc0d3r** [comment]
Can you try to update to v2.2.0? The crash report line number doesn't do anything with blend shapes in the latest version so I don't know where it is actually crashing.
If it still crashes with the newest version you could try sending me the problematic mesh file so I can have a look at it.

**Comment by teehzero** [comment]
Was able to fix by setting FBX rig to 'None' and then 'Humanoid'. I can no longer reproduce the issue.

**Comment by teehzero** [comment]
https://i.imgur.com/QKV0FFl.png
If any of the viseme blendshapes are set to `-none-` the optimize fails.

**Comment by d4rkc0d3r** [comment]
Ah very nice, I can reproduce it with that on my end!
