### ISSUE TITLE
d4rkAvatarOptimizer.cs Error CS0246: The type or namespace name 'IEditorOnly' could not be found

### ISSUE THREAD

**Issue by KingAzaz** [d4rkc0d3r/d4rkAvatarOptimizer#39]
Freshly imported this into my project and have been getting this without fail. Tried importing it into a brand-new project and getting the same thing. Not sure exactly how to fix it. Unity won't go into play mode because of this, as well.

`Packages\d4rkpl4y3r.d4rkavataroptimizer\Editor\d4rkAvatarOptimizer.cs(27,51): error CS0246: The type or namespace name 'IEditorOnly' could not be found (are you missing a using directive or an assembly reference?)`

Using the 'https://d4rkc0d3r.github.io/vpm-repos/main.json' repository to import the optimizer

**Comment by d4rkc0d3r** [comment]
This error message sounds like you are using an outdated avatar & base sdk. Try to update both to 3.2.0 if they aren't already.
