### ISSUE TITLE
Out of range error cancelling optimisation

### ISSUE THREAD

**Issue by rskskr** [d4rkc0d3r/d4rkAvatarOptimizer#4]
When trying to optimise with only Merge Different Property Materials selected, the process is aborted with the error below. The avatar also contains 3 unparsable materials (out of a total of 11), if that's relevant?

![Unity_n98yetFWqy](https://user-images.githubusercontent.com/52654735/185387524-38a99a24-4a26-4c69-8e4d-3022be444878.png)

**Comment by rskskr** [comment]
It seems this shader has an invalid 0 index for `optimizedShader[i][0]` on line 1115.

![Unity_BZUZoHRY6z](https://user-images.githubusercontent.com/52654735/185395360-516f46d2-fab3-4901-b785-a3e14b59576b.png)

**Comment by d4rkc0d3r** [comment]
I am unable to reproduce the error on my end with this amount of info. Unlit/Color is a unity builtin shader and should count as a unparsable material. "Unparsable materials" should get ignored entirely when optimizing so I am not sure if that one is your problem. Can you check the debug info foldout if it is indeed correctly listed as unparsable?

**Comment by rskskr** [comment]
Hmm, strangely it isn't listed as unparsable on my end. Only a few liltoon materials are.

**Comment by d4rkc0d3r** [comment]
I tried counting 0 parsed lines as "unparsable material", can you dl newest version from https://github.com/d4rkc0d3r/d4rkAvatarOptimizer/archive/refs/heads/main.zip and see if that fixes it? Delete the old version first!

**Comment by rskskr** [comment]
That fixed it! Thank you!
