### ISSUE TITLE
UnityExceptions; Unable to optimize post weird behaviour

### ISSUE THREAD

**Issue by Yurichtofen** [d4rkc0d3r/d4rkAvatarOptimizer#40]
KeyNotFoundException: The given key was not present in the dictionary.
System.Collections.Generic.Dictionary`2[TKey,TValue].get_Item (TKey key) (at <eae584ce26bc40229c1b1aa476bfa589>:0)
d4rkAvatarOptimizer+<>c__DisplayClass120_1.<CombineAndOptimizeMaterials>b__20 (d4rkAvatarOptimizer+MaterialSlot slot) (at Packages/d4rkpl4y3r.d4rkavataroptimizer/Editor/d4rkAvatarOptimizer.cs:2464)
System.Linq.Enumerable+SelectListIterator`2[TSource,TResult].MoveNext () (at <351e49e2a5bf4fd6beabb458ce2255f3>:0)
System.Linq.Set`1[TElement].UnionWith (System.Collections.Generic.IEnumerable`1[T] other) (at <351e49e2a5bf4fd6beabb458ce2255f3>:0)
System.Linq.Enumerable+DistinctIterator`1[TSource].FillSet () (at <351e49e2a5bf4fd6beabb458ce2255f3>:0)
System.Linq.Enumerable+DistinctIterator`1[TSource].ToList () (at <351e49e2a5bf4fd6beabb458ce2255f3>:0)
System.Linq.Enumerable.ToList[TSource] (System.Collections.Generic.IEnumerable`1[T] source) (at <351e49e2a5bf4fd6beabb458ce2255f3>:0)
d4rkAvatarOptimizer+<>c__DisplayClass120_1.<CombineAndOptimizeMaterials>b__4 (System.Collections.Generic.List`1[T] list) (at Packages/d4rkpl4y3r.d4rkavataroptimizer/Editor/d4rkAvatarOptimizer.cs:2464)
System.Linq.Enumerable+SelectListIterator`2[TSource,TResult].ToList () (at <351e49e2a5bf4fd6beabb458ce2255f3>:0)
System.Linq.Enumerable.ToList[TSource] (System.Collections.Generic.IEnumerable`1[T] source) (at <351e49e2a5bf4fd6beabb458ce2255f3>:0)
d4rkAvatarOptimizer.CombineAndOptimizeMaterials () (at Packages/d4rkpl4y3r.d4rkavataroptimizer/Editor/d4rkAvatarOptimizer.cs:2464)
d4rkAvatarOptimizer.Optimize () (at Packages/d4rkpl4y3r.d4rkavataroptimizer/Editor/d4rkAvatarOptimizer.cs:131)
d4rkAvatarOptimizerEditor.OnInspectorGUI () (at Packages/d4rkpl4y3r.d4rkavataroptimizer/Editor/d4rkAvatarOptimizerEditor.cs:93)
UnityEditor.UIElements.InspectorElement+<>c__DisplayClass58_0.<CreateIMGUIInspectorFromEditor>b__0 () (at <a259d3c004024353a2c217da97495055>:0)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)

//////////////////

Couldn't create asset file!
UnityEngine.StackTraceUtility:ExtractStackTrace ()
d4rkAvatarOptimizer:CreateUniqueAsset (UnityEngine.Object,string) (at Packages/d4rkpl4y3r.d4rkavataroptimizer/Editor/d4rkAvatarOptimizer.cs:293)
d4rkAvatarOptimizer:FixAnimationClipPaths (UnityEngine.AnimationClip) (at Packages/d4rkpl4y3r.d4rkavataroptimizer/Editor/d4rkAvatarOptimizer.cs:602)
d4rkAvatarOptimizer:FixAllAnimationPaths () (at Packages/d4rkpl4y3r.d4rkavataroptimizer/Editor/d4rkAvatarOptimizer.cs:703)
d4rkAvatarOptimizer:Optimize () (at Packages/d4rkpl4y3r.d4rkavataroptimizer/Editor/d4rkAvatarOptimizer.cs:144)
d4rkAvatarOptimizerEditor:OnInspectorGUI () (at Packages/d4rkpl4y3r.d4rkavataroptimizer/Editor/d4rkAvatarOptimizerEditor.cs:93)
UnityEngine.GUIUtility:ProcessEvent (int,intptr)

//////////////////

UnityException: Creating asset at path  failed.
d4rkAvatarOptimizer.CreateUniqueAsset (UnityEngine.Object asset, System.String name) (at Packages/d4rkpl4y3r.d4rkavataroptimizer/Editor/d4rkAvatarOptimizer.cs:293)
d4rkAvatarOptimizer.FixAnimationClipPaths (UnityEngine.AnimationClip clip) (at Packages/d4rkpl4y3r.d4rkavataroptimizer/Editor/d4rkAvatarOptimizer.cs:602)
d4rkAvatarOptimizer.FixAllAnimationPaths () (at Packages/d4rkpl4y3r.d4rkavataroptimizer/Editor/d4rkAvatarOptimizer.cs:703)
d4rkAvatarOptimizer.Optimize () (at Packages/d4rkpl4y3r.d4rkavataroptimizer/Editor/d4rkAvatarOptimizer.cs:144)
d4rkAvatarOptimizerEditor.OnInspectorGUI () (at Packages/d4rkpl4y3r.d4rkavataroptimizer/Editor/d4rkAvatarOptimizerEditor.cs:93)
UnityEditor.UIElements.InspectorElement+<>c__DisplayClass58_0.<CreateIMGUIInspectorFromEditor>b__0 () (at <a259d3c004024353a2c217da97495055>:0)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)

**Comment by d4rkc0d3r** [comment]
Unfortunately I can't really come up with any ideas on what the problem could be.  
It's just crashing in the part where I tell unity to make asset files for the new animations. Considering that at that point it already managed to create assets for materials & meshes it can't be a generic issue like file read/write issues.  
The only other idea is that maybe some animation of yours has a weird name that unity doesn't like to create an asset for...

You could try to find the animations that cause it by putting all meshes into the exclusion list. If it works, you can then start to remove them from the exclusions one by one until it stops working again. Then you can look through your animations that affect that mesh to see if something about the animation names seems off.

**Comment by d4rkc0d3r** [comment]
Ok, I can finally reproduce this issue. Thanks for the detailed testing!
The issue is that the animation has a slash in it's name.
