### ISSUE TITLE
Material Swap uses incorrect UV

### ISSUE THREAD

**Issue by teehzero** [d4rkc0d3r/d4rkAvatarOptimizer#41]
These material swaps don't appear to be taking UVs into account. I'm not actually very sure what's going wrong here.
https://www.youtube.com/watch?v=YKbd8XlAt5A

**Comment by d4rkc0d3r** [comment]
Can you elaborate a bit further on what your problem actually is? The linked video is an audio link tutorial which doesn't seem to mention material swaps at all?

**Comment by d4rkc0d3r** [comment]
It might be the unity material swap bug. The editor version doesn't have the bug fix for that but the live vrc version does, so it might be worth to quickly test if it also happens in-game.

For reference, this is the bug I am talking about: https://issuetracker.unity3d.com/issues/material-is-applied-to-two-slots-when-applying-material-to-a-single-slot-while-recording-animation

**Comment by teehzero** [comment]
Exactly as you said. Thank you much! I have no more need for this issue.
