### ISSUE TITLE
VRCFury Compatibility

### ISSUE THREAD

**Issue by laxdragon** [d4rkc0d3r/d4rkAvatarOptimizer#42]
This breaks all toggles and items that use VRCFury.

https://github.com/VRCFury/VRCFury

Verified by converting avatar and uploading a test, and none of the item toggles that would show items enabled by VRCFury would work.

**Comment by d4rkc0d3r** [comment]
How did you use both tools together? If you run the optimizer before Fury it will break predictably. If you just upload the avatar, the different callback order of the two scripts should make it so Fury runs before my optimizer and things should be fine.

**Comment by laxdragon** [comment]
I did do the pre-convert as new instance instead of just doing the conversion at upload time. I'll try the at upload, and see if the toggles still work.

**Comment by d4rkc0d3r** [comment]
Is there still a problem for you with the toggles? I did a small test myself and at least simple toggles worked fine.

It now also disables the optimize button while a VRCFury component is on the avatar to prevent accidentally applying things in the wrong order.

**Comment by d4rkc0d3r** [comment]
I'm going to close this as there was no more follow up and several people use the optimizer with VRCFury just fine. Feel free to reopen or make a new issue if there are more specific issues with it.
