### ISSUE TITLE
Extra check/viewing with fallback shaders not being a thing

### ISSUE THREAD

**Issue by arianwen27** [d4rkc0d3r/d4rkAvatarOptimizer#44]
Not too sure how to word this but there's no way to view how optimised avatars will look when a fallback shader is used.
Currently, the only way to view the avatar with shaders unloaded is with another person and vrc account.

This is a rather large issue in my eyes as the optimiser could merge meshes together that with the shader, look like normal. But when a user does not have the shader loaded, they could be seeing the avatar very differently.

Say I had an asset that I wanted off by default but could toggle on. The optimisation process might merge it with a mesh that's always displayed. To a user that doesn't have the shader loaded, this means they will see the asset that is supposed to be hidden while the user of the avatar is unaware. An example of this, the optimiser might merge an aspect of a 'dps asset' into the body. To the user and their friends, nothing is showing. To a user with shaders disabled, they'd be seeing something that was not intended to be shown. I know dps meshes are usually auto except but the attached asset might have other meshes or materials that are equally not showable.

Having to get a friend to disable their shaders and check what optimised avatars look like every time I want to update an avatar is a real pain. Some easy way to view what the avatar looks like to a user with shaders disabled would help a ton.

**Comment by d4rkc0d3r** [comment]
>Not too sure how to word this but there's no way to view how optimised avatars will look when a fallback shader is used.
Currently, the only way to view the avatar with shaders unloaded is with another person and vrc account.

Yeah, this is also true for non optimized avatars. It's been a pain point that I have complained about a lot, but we never got a preview in the sdk to debug our fallback shaders.

> Some easy way to view what the avatar looks like to a user with shaders disabled would help a ton.

Yes. Yes it would. Complaint to VRChat about it. From the information available to me I can't reimplement the shader fallback system on my side...
