### ISSUE TITLE
Separate "exclusion list" windows and bake button

### ISSUE THREAD

**Issue by jerryzmtz** [d4rkc0d3r/d4rkAvatarOptimizer#51]
It is too slow to make any modifications on the script attached to the avatar. 

I am facing an issue where after optimizations, "some" of the toggles attached to hand bones failed to be previewed in editor play mode. So before optimization, Object A is default off and could be toggled on with ParameterA true. However, after optimizations, it is default off and could not be toggled on, even if the remapped animations and parameters/menu have no problems. This only happens with gesture manager in editor play mode. I want to provide more information, but it takes years to add/remove exclusion lists and bake optimalized copies to locate which asset is causing problems.

It turns out that a performant avatar will not face this issue of editor's bad performance. But in fact, the bad the avatar is, the more optimization is in need. Therefore, I think a separate exclusion list window will help a lot. Debug info is also too hard to be read, maybe a button to save log locally will benefit both the users and developers.

**Comment by d4rkc0d3r** [comment]
hmm I could make the preview values not recalculate if the last time it did so took too long and add a button to manually recalculate.

currently it recalculates anytime an option or exclusion item gets changed. actually I think even clicking a foldout does cause a recalc, that should definitely be changed.

**Comment by d4rkc0d3r** [comment]
This should be addressed by the timeout that stops the automatic recalculation for the preview if it takes too long. Feel free to make a new issue/reopen if its still a problem.
