### ISSUE TITLE
unsupported shader to add liltoon

### ISSUE THREAD

**Issue by theyada86** [d4rkc0d3r/d4rkAvatarOptimizer#53]
Message:
"Unparsable materials
liltoon shaders are not supported"

With latest from https://lilxyzw.github.io/lilToon/#/

**Comment by d4rkc0d3r** [comment]
liltoon shader does several things that are incompatible with my optimizer. Lots of them are very fundamental to the shader and almost impossible from my side to support.  
I assume you are asking me to add full support for liltoon shaders? In which case that will not happen from my side.

btw, unparsable materials still support all the basic optimizations, they just disable shader toggles and advanced material merging for themselves.
