### ISSUE TITLE
(modular avatar compatibility)Compatibility support for NDMF

### ISSUE THREAD

**Issue by ni1chigo2115** [d4rkc0d3r/d4rkAvatarOptimizer#55]
Although not yet in its official version, modular avatar is in the process of introducing NDMF, a non-destructive modification system compatibility system.
It seems to me that this process needs to be taken into consideration when dealing with modular avatar in the future.

https://ndmf.nadena.dev
--------
(modular avatar互換性)NDMFへの互換性対応
まだ正式版ではないですが、modular avatarがNDMFという非破壊改変システムの互換システムの導入を進めています。
今後modular avatarへの対応を行う場合、この処理を考慮する必要があるように思います。

**Comment by d4rkc0d3r** [comment]
I have not heard of any incompatibilities with NDMF yet so I will close this. If some concrete issues arise please make a bug report for that.
