### ISSUE TITLE
Set fallback shader to Hidden instead of exclusion for penetrators

### ISSUE THREAD

**Issue by jerryzmtz** [d4rkc0d3r/d4rkAvatarOptimizer#57]
I have confirmed that when fallback shader is set to Hidden, it will not be seen after optimizations. So I think maybe it is a good idea to include penetrators in optimizations but set its fallback shader to Hidden

**Comment by d4rkc0d3r** [comment]
Penetrators aren't merged into other meshes for two reasons. The first is the one you think of which is that they should not show up when shaders are blocked. But the second one is function. The penetrators rely on the root transform, so merging them with something else would mess up their behaviour.
