### ISSUE TITLE
NullReferenceException: Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by uwuclara** [d4rkc0d3r/d4rkAvatarOptimizer#6]
I'm having a trouble with NullReferenceEXception. I tried 2 projects, am I doing something wrong/missing? I import it, add component and start the optimization. I get this error and left with new gameobject that has "(Broken)" in it. The only values that change are mesh renderers to skinned mesh renderers and that's it. If I try unchecking Merge Static Meshes as Skinned it still errors out. I'm using the newest VRCSDK.

![image](https://user-images.githubusercontent.com/31383052/186126800-3fb22468-b725-47ff-9cad-3ceb77cd32f1.png)

**Comment by d4rkc0d3r** [comment]
seems like sometimes skinned meshes reference a `null` bone. well I fixed it, you can dl the fixed version here: https://github.com/d4rkc0d3r/d4rkAvatarOptimizer/archive/refs/heads/main.zip
