### ISSUE TITLE
Max shader keywords exceeded on optimize

### ISSUE THREAD

**Issue by teehzero** [d4rkc0d3r/d4rkAvatarOptimizer#62]
hiii 💜💜💜

d4rk Avatar Optimizer 3.2.2
Poi Pro 9.0a13
VRSGLI Shader Pack v1.2

https://i.imgur.com/JWIe2XG.png
https://i.imgur.com/hPGn3Lv.png
https://i.imgur.com/BdxPmVG.png
The failing material is Poi Pro GeoDissolve with VRSLGI module installed. Functioning materials are Poi Pro with VRSLGI module installed. Let me know if there's anything else I can provide to help.

**Comment by teehzero** [comment]
After enabling AudioLink and outlines on a different material, the previously failing shader now compiles

**Comment by d4rkc0d3r** [comment]
I'm just not gonna deal with that as shader keywords will be practically infinite once we get a 2022 unity sdk.
