### ISSUE TITLE
Adding dummy animation can lead to WD issues

### ISSUE THREAD

**Issue by LuciBlack13** [d4rkc0d3r/d4rkAvatarOptimizer#63]
Adding an empty dummy animation to animator states that have no animation specified can lead to WD issues under certain circumstances.

In my case I have a couple layers where I purposefully mixed WD OFF with WD ON states - the WD OFF ones being empty states.
Adding an empty animation clip to those states leads to WD issues.

It would be greatly appreciated if there was an option to disable the filling of empty states with a dummy animation.

**Comment by d4rkc0d3r** [comment]
hmm, I'll probably just get rid of that entirely instead of making yet another option.

"fixing" something isn't really the right place for the optimizer anyways and this feature comes from a time when this was pretty much just used by myself before any public releases.
