### ISSUE TITLE
Add Documentation of using with VRCFury

### ISSUE THREAD

**Issue by Haldmaster** [d4rkc0d3r/d4rkAvatarOptimizer#64]
Hi,
I want to use this tool in an Avatar Project.
I am using VRCFury and I have read in previous issues, that this tool is able to work (somewhat) nicely with it.
But I am not very fit in reading C# code to understand how this tool is working with VRCFury.
Can I request for the addition of notes in the documentation on how to use this tool next to VRCFury.

Thank you
HM

**Comment by d4rkc0d3r** [comment]
You don't do anything special when using it with fury. The optimizer should just run after fury on upload if the component is on the avatar.
One thing to keep in mind when using it with fury or other non destructive tools is that the preview stats of the optimizer are wrong in that case as it doesn't take into account what fury will do for just the preview. The UI will already tell you this too if there is a VRCFury component on the avatar.
So I'm not exactly sure what you want me to add to the documentation.

**Comment by Haldmaster** [comment]
it was just that i was not sure if there was anything to consider, when using both both tools. they might get into each others way, but thank you
