### ISSUE TITLE
Shader Toggle Malfunction: Loss of Animation in Combined Skinned Meshes Utilizing Liltoon Fur Shader

### ISSUE THREAD

**Issue by jerryzmtz** [d4rkc0d3r/d4rkAvatarOptimizer#66]
Description:
I've discovered a compatibility issue involving the d4rkAvatarOptimizer plugin in Unity 2019, particularly when used alongside VRChat SDK 3.4.1, that affects the Liltoon Fur Shader. The expectation is for the shader's material properties to be animated correctly after the optimization process. 

Issue Details:
Affected Shader: Liltoon Fur Shader
Settings: "Use shader toggles" is on.
Expected Behavior: Post-optimization, the material properties of the shader are anticipated to animate correctly, maintaining their intended functionality and appearance.
Observed Behavior: After optimization, there is a notable issue with the animation of material properties for combined skinned meshes using the Liltoon Fur Shader. Specifically, these material properties fail to animate as expected.

Steps to Reproduce:

Pre-Optimization Setup:
Enable the "Monochrome" toggle from expression menu. This changes the "Monochrome Lighting" material property from 0 to 0.5, as shown in the Screenshot1.
Note: This setup works correctly if "Use Shader Toggles" is unchecked, with other settings remaining the same, as shown in the Screenshot1

Post-Optimization Issues:
With "Use Shader Toggles" enabled and settings as shown in the Screenshot1, the optimized copy exhibits issues as shown in the Screenshot2.
Material properties of Liltoon Fur Shader on combined skinned meshes (e.g., "pajamas(combined)" and "socks(combined)") are incorrectly changed.
"pajamas(combined)" is a combination of four skinned meshes, as depicted in the provided screenshot3.
Skinned meshes that are not combined (e.g., the drawer) animate correctly.

![Screenshot_5](https://github.com/d4rkc0d3r/d4rkAvatarOptimizer/assets/26083118/1a1c0cc1-6107-4082-91f9-23748b1a2fbd)
![Screenshot_6](https://github.com/d4rkc0d3r/d4rkAvatarOptimizer/assets/26083118/0b624f05-ff2c-4105-87e3-e2a4a73c5c93)
![Screenshot_7](https://github.com/d4rkc0d3r/d4rkAvatarOptimizer/assets/26083118/3ce87ecc-ff11-48a6-94de-bf670aa778a5)

**Comment by d4rkc0d3r** [comment]
hmm I remember adding a check specifically because of liltoon fur that checks if the shader name contains lilToon to make sure the optimizer doesn't try anything funny on it.
Can you check in the debug info that it correctly lists the fur shader as not supported?
(Unsupported shaders are supposed to be treated as if "Use Shader Toggles" is turned off)

**Comment by jerryzmtz** [comment]
> hmm I remember adding a check specifically because of liltoon fur that checks if the shader name contains lilToon to make sure the optimizer doesn't try anything funny on it. Can you check in the debug info that it correctly lists the fur shader as not supported? (Unsupported shaders are supposed to be treated as if "Use Shader Toggles" is turned off)

It is correctly listed in unparsable materials.


![Screenshot_5](https://github.com/d4rkc0d3r/d4rkAvatarOptimizer/assets/26083118/1f54f271-0a1f-4e68-87bc-886c4d17c8e5)
![Screenshot_6](https://github.com/d4rkc0d3r/d4rkAvatarOptimizer/assets/26083118/1d8912aa-dc6d-45cc-8ad0-0449dcc0f008)

**Comment by d4rkc0d3r** [comment]
one last question. do the material property animations rely on write defaults?
because the default value of a material property animation is whatever the first material of a mesh renderer has the property set as which can be really confusing.
thanks for all the info so far.

**Comment by jerryzmtz** [comment]
> one last question. do the material property animations rely on write defaults? because the default value of a material property animation is whatever the first material of a mesh renderer has the property set as which can be really confusing. thanks for all the info so far.

I have checked with a blank avatar with only one toggle: Monochrome. In this example, all the poiyomi shader meshes are combined as "Body", while all the liltoon fur shader meshes are combined as "Pajamas$String" I have located the only animation and notice that although liltoon fur shader is left untouched, material properties of liltoon fur shader is renamed to shader toggles.

As for write defaults, I always unify it to WD ON. But I am not sure what do you mean by "rely on".

![Screenshot_7](https://github.com/d4rkc0d3r/d4rkAvatarOptimizer/assets/26083118/20a9f32e-4c52-46f4-ba3a-be20f9d86239)

**Comment by jerryzmtz** [comment]
This is an example without "use shader toggle". In this case, "Pajamas$String11" still exist so it works as expected.
![Screenshot_8](https://github.com/d4rkc0d3r/d4rkAvatarOptimizer/assets/26083118/403fbeb6-b06e-4b56-b594-9376c541b305)

**Comment by d4rkc0d3r** [comment]
> As for write defaults, I always unify it to WD ON. But I am not sure what do you mean by "rely on".

With that I meant if you have animations for both states or just 1 animation state. WD ON can still do 2 animations like WD OFF and then it wouldn't matter if the states have WD ON or OFF actually set.

But as you described this shouldn't matter in your case.

Thanks to your detailed info I now know what causes the issue, thanks a bunch!
