### ISSUE TITLE
Run VRCFury before optimizing with "Create Optimized Copy."

### ISSUE THREAD

**Issue by Kikasuru** [d4rkc0d3r/d4rkAvatarOptimizer#69]
VRCFury does not run whenever the `Create Optimized Copy` button is pressed, which would be very helpful for testing before upload.

I _can_ create an editor test copy with VRCFury by going to `Tools>VRCFury>Build an Editor Test Copy` but it would be super nice if it just _worked_.

**Comment by d4rkc0d3r** [comment]
looks like vrc fury changed something then. the button should not be pressable if you have a fury component on the avatar

**Comment by Kikasuru** [comment]
Yeah, found that out later with a friend's project.  I have VRCFury components within other GameObjects parented to the avatar, but none on the GameObject with the avatar descriptor.  I'm guessing the optimizer only checks the GameObject it's in?

**Comment by d4rkc0d3r** [comment]
Ah that explains it then. Yeah it only checks the root gameobject for a VRCFury component right now.

**Comment by Toys0125** [comment]
Wanted to post that VRCFury now runs D4rk's optimizer when building a test copy and other similar tools.
