### ISSUE TITLE
Null pointer error on Create Optimized Copy

### ISSUE THREAD

**Issue by Odel** [d4rkc0d3r/d4rkAvatarOptimizer#7]
Getting the following when running the optimizer, it does spit out a copy but as far as I can tell no optimizations are being applied

NullReferenceException: Object reference not set to an instance of an object
d4rkAvatarOptimizerEditor.OptimizeMaterialSwapMaterials () (at Assets/d4rkAvatarOptimizer/src/d4rkAvatarOptimizerEditor.cs:551)
d4rkAvatarOptimizerEditor.Optimize (UnityEngine.GameObject toOptimize) (at Assets/d4rkAvatarOptimizer/src/d4rkAvatarOptimizerEditor.cs:2399)
d4rkAvatarOptimizerEditor.OnInspectorGUI () (at Assets/d4rkAvatarOptimizer/src/d4rkAvatarOptimizerEditor.cs:2798)
UnityEditor.UIElements.InspectorElement+<>c__DisplayClass58_0.<CreateIMGUIInspectorFromEditor>b__0 () (at <a259d3c004024353a2c217da97495055>:0)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)

Let me know any other information you need, as I'm unsure what is relevant

**Comment by d4rkc0d3r** [comment]
This was caused by an animation having a material swap referencing a path that doesn't exist on the model.
Get the fix here: https://github.com/d4rkc0d3r/d4rkAvatarOptimizer/archive/refs/heads/main.zip
