### ISSUE TITLE
Feature Request: Deleting polygons that are associated with shrink blendshapes

### ISSUE THREAD

**Issue by Kikasuru** [d4rkc0d3r/d4rkAvatarOptimizer#70]
It'd be nice if during the blendshape baking process, it'd also check if it's in a list of (generated and editable by the user, not predefined) shrink blendshapes commonly associated with booth avatars, and delete all polys associated with them, since they won't be there anyways.

**Comment by d4rkc0d3r** [comment]
Hai just added a feature like this to prefabulous avatar: https://docs.hai-vr.dev/docs/products/prefabulous-avatar/hai-components/delete-polygons

I won't be adding this to the optimizer, instead you should use that tool. The goal with the optimizer is to have basically no manual setup required.
