### ISSUE TITLE
The VRCSDK build was aborted because the VRCSDKPreprocessAvatarCallback 'AvatarBuildHook' reported a failure.

### ISSUE THREAD

**Issue by Atopos-07** [d4rkc0d3r/d4rkAvatarOptimizer#71]
You cannot upload your avatar.
I am getting the following error and my Unity version is 2022.3.6f1.
Does this version not work yet?

Refreshing native plugins compatible for Editor in 10.61 ms, found 4 plugins.
Preloading 2 native plugins for Editor in 0.09 ms.
Asset Pipeline Refresh (id=fbcd2e44ca5170841a6860d459e9a2c7): Total: 0.109 seconds - Initiated by StopAssetImportingV2(NoUpdateAssetOptions)
Start importing Packages/d4rkpl4y3r.d4rkavataroptimizer/TrashBin using Guid(b64dde50c31b8c64cac61625fa80562a) Importer(-1,00000000000000000000000000000000)  -> (artifact id: 'a205be73cc644c11893863d0f56fef37') in 0.003109 seconds
Refreshing native plugins compatible for Editor in 10.86 ms, found 4 plugins.
Preloading 2 native plugins for Editor in 0.09 ms.
Asset Pipeline Refresh (id=069be3bf6d765da4eb989bbcfc66d4c8): Total: 0.113 seconds - Initiated by StopAssetImportingV2(NoUpdateAssetOptions)
System.InvalidOperationException: Avatar is null.
  at UnityEngine.Animator.GetBoneTransform (UnityEngine.HumanBodyBones humanBoneId) [0x00011] in <9802f153e66043958995cd88a8668a6e>:0 
  at d4rkAvatarOptimizer.FindAllMovingTransforms () [0x00238] in .\Packages\d4rkpl4y3r.d4rkavataroptimizer\Editor\d4rkAvatarOptimizer.cs:2291 
  at d4rkAvatarOptimizer.FindAllUnmovingTransforms () [0x00029] in .\Packages\d4rkpl4y3r.d4rkavataroptimizer\Editor\d4rkAvatarOptimizer.cs:2346 
  at d4rkAvatarOptimizer.FindMovingParent () [0x00000] in .\Packages\d4rkpl4y3r.d4rkavataroptimizer\Editor\d4rkAvatarOptimizer.cs:3425 
  at d4rkAvatarOptimizer.CombineSkinnedMeshes () [0x0003b] in .\Packages\d4rkpl4y3r.d4rkavataroptimizer\Editor\d4rkAvatarOptimizer.cs:3444 
  at d4rkAvatarOptimizer.Optimize () [0x00184] in .\Packages\d4rkpl4y3r.d4rkavataroptimizer\Editor\d4rkAvatarOptimizer.cs:149 
  at d4rkpl4y3r.AvatarOptimizer.AvatarBuildHook.OnPreprocessAvatar (UnityEngine.GameObject avatarGameObject) [0x00045] in .\Packages\d4rkpl4y3r.d4rkavataroptimizer\Editor\AvatarBuildHook.cs:37 
UnityEngine.StackTraceUtility:ExtractStackTrace ()
UnityEngine.DebugLogHandler:LogFormat (UnityEngine.LogType,UnityEngine.Object,string,object[])
UnityEngine.Logger:Log (UnityEngine.LogType,object)
UnityEngine.Debug:LogError (object)
d4rkpl4y3r.AvatarOptimizer.AvatarBuildHook:OnPreprocessAvatar (UnityEngine.GameObject) (at ./Packages/d4rkpl4y3r.d4rkavataroptimizer/Editor/AvatarBuildHook.cs:42)
VRC.SDKBase.Editor.BuildPipeline.VRCBuildPipelineCallbacks:OnPreprocessAvatar (UnityEngine.GameObject)
VRC.SDK3.Builder.VRCAvatarBuilder:ExportCurrentAvatarResource (UnityEngine.Object,bool,bool,string&,System.Action`1<string>,System.Action`1<object>)
VRC.SDK3.Builder.VRCAvatarBuilder:ExportAvatarBlueprint (UnityEngine.GameObject)
VRC.SDK3A.Editor.VRCSdkControlPanelAvatarBuilder/<Build>d__106:MoveNext () (at ./Packages/com.vrchat.avatars/Editor/VRCSDK/SDK3A/VRCSdkControlPanelAvatarBuilder.cs:2040)
System.Runtime.CompilerServices.AsyncMethodBuilderCore/MoveNextRunner:InvokeMoveNext (object)
System.Threading.ExecutionContext:RunInternal (System.Threading.ExecutionContext,System.Threading.ContextCallback,object,bool)
System.Threading.ExecutionContext:Run (System.Threading.ExecutionContext,System.Threading.ContextCallback,object,bool)
System.Runtime.CompilerServices.AsyncMethodBuilderCore/MoveNextRunner:Run ()
System.Threading.Tasks.SynchronizationContextAwaitTaskContinuation/<>c:<.cctor>b__7_0 (object)
UnityEngine.UnitySynchronizationContext/WorkRequest:Invoke ()
UnityEngine.UnitySynchronizationContext:Exec ()
UnityEngine.UnitySynchronizationContext:ExecuteTasks ()

(Filename: ./Packages/d4rkpl4y3r.d4rkavataroptimizer/Editor/AvatarBuildHook.cs Line: 42)

The VRCSDK build was aborted because the VRCSDKPreprocessAvatarCallback 'AvatarBuildHook' reported a failure.

**Comment by d4rkc0d3r** [comment]
Same issue as https://github.com/d4rkc0d3r/d4rkAvatarOptimizer/issues/65

There is an extra animator somewhere on your avatar. If you remove it it will work. Otherwise the bug is new in unity 2022 and will be fixed whenever I finish the next release.

**Comment by d4rkc0d3r** [comment]
This bug has been fixed in the optimizer for ages now. Make sure you are on the newest version. If you still have issues then make a new bug report with the appropriate info that helps me troubleshoot like this stacktrace in this issue.
