### ISSUE TITLE
invalid paths in ZIP

### ISSUE THREAD

**Issue by HookedBehemoth** [d4rkc0d3r/d4rkAvatarOptimizer#75]
I have no idea how you managed to do this but the ZIP contains funky paths that incidentally work on winblows.
Trying to import this on GNU+Linux makes Unity hang. Please fix. :*
![image](https://github.com/d4rkc0d3r/d4rkAvatarOptimizer/assets/22580720/609966e8-4559-424e-8e91-413b316b2487)
![image](https://github.com/d4rkc0d3r/d4rkAvatarOptimizer/assets/22580720/bbc36dee-5500-42b4-b3c5-022758eb89c2)

**Comment by d4rkc0d3r** [comment]
One tactical `.Replace('\\', '/')` later and it should be fixed for 3.4.0
