### ISSUE TITLE
Material property animations not work after optimization

### ISSUE THREAD

**Issue by jerryzmtz** [d4rkc0d3r/d4rkAvatarOptimizer#77]
Without Optimizer, Material property animations could correctly change the _LightMinLight of liltoon materials of the whole avatar. However, after optimizations, only parts of the dress could be animated. It is kind of like the previous issues: https://github.com/d4rkc0d3r/d4rkAvatarOptimizer/issues/66

[IssueReport.zip](https://github.com/d4rkc0d3r/d4rkAvatarOptimizer/files/14206209/IssueReport.zip)

**Comment by d4rkc0d3r** [comment]
This is very probably already fixed by https://github.com/d4rkc0d3r/d4rkAvatarOptimizer/commit/630795804284154408a3a02803dc38348da7728f for a future release.
I can see from your screenshots that the miss matched animations indeed are missing that `material.` prefix for the animation property name.

**Comment by d4rkc0d3r** [comment]
3.4.0 is out and has this fix
