### ISSUE TITLE
[Feature Request] Optimize String Length for Material and Texture Names

### ISSUE THREAD

**Issue by sneezingabbey** [d4rkc0d3r/d4rkAvatarOptimizer#78]
While I acknowledge this might seem more like an idea than a concrete request, I believe it's worth considering. String comparisons can be slow due to algorithmic complexities, particularly as string length increases. My proposal involves automatically renaming materials and textures to shorter, randomly generated strings upon upload. For instance, Substance Painter often generates lengthy texture names. However, I understand there might be concerns about the potential performance gain being negligible. Let me know what do you think.

**Comment by d4rkc0d3r** [comment]
Unless anyone can show that this has any measurable performance impact I won't be doing that.

This would reduce debug ability of the generated assets quite a bit.
