### ISSUE TITLE
Null Reference

### ISSUE THREAD

**Issue by MLuccia** [d4rkc0d3r/d4rkAvatarOptimizer#79]
Having a strange exception with materials, aside from the console log, the only other thing I noticed is that the preview displays a X number of material slots, however, in vrchat the number is different.

I've no idea what could be the issue, as far I can tell it just started randomly.

![image](https://github.com/d4rkc0d3r/d4rkAvatarOptimizer/assets/75513867/4b72914f-8414-4c56-9abb-14aa7c9ddc5e)

current options:
![image](https://github.com/d4rkc0d3r/d4rkAvatarOptimizer/assets/75513867/eb7c7a0b-018a-45a2-b0c5-61616903d94b)

`

**Comment by d4rkc0d3r** [comment]
This seems to be caused by one of your renderers having no mesh in them.

**Comment by MLuccia** [comment]
You sure that's the problem? When a search for MeshRenderer/Filter, all the objects have both

**Comment by d4rkc0d3r** [comment]
Did you try it with 3.4.0 yet? If it still happens for you, reopen the issue.
