### ISSUE TITLE
Shader issue?

### ISSUE THREAD

**Issue by uwuclara** [d4rkc0d3r/d4rkAvatarOptimizer#8]
Optimizer failing generating shader. Using Sunao Shader and a pure 512x512 one color texute.

![image](https://user-images.githubusercontent.com/31383052/186740858-b51a7765-53f4-4ca5-8752-76fea96acc27.png)
![image](https://user-images.githubusercontent.com/31383052/186738914-10e5ec87-37e9-4293-b693-db10e5355ab9.png)
![image](https://user-images.githubusercontent.com/31383052/186739115-2e6a5dc4-4433-49da-b650-17f5bb6ca3a3.png)
![image](https://user-images.githubusercontent.com/31383052/186739176-cb2400e6-2c60-4a74-b51b-72e3f73342c9.png)

**Comment by d4rkc0d3r** [comment]
Follow the [why my shader pink](https://github.com/d4rkc0d3r/d4rkAvatarOptimizer#why-my-shader-pink) section of the readme to export the material and put it in this issue.

**Comment by uwuclara** [comment]
![image](https://user-images.githubusercontent.com/31383052/186758180-0256aeab-23d0-4600-a73a-ef3587afa5de.png)


[frame.zip](https://github.com/d4rkc0d3r/d4rkAvatarOptimizer/files/9427880/frame.zip)
