### ISSUE TITLE
Shader Error with 3.4.0 on Poiyomi when matcap has no matcap texture

### ISSUE THREAD

**Issue by Auros** [d4rkc0d3r/d4rkAvatarOptimizer#80]
Tested on Poiyomi 9.0.38 and 9.0.40

Providing a Matcap fixes it, but I don't need one for this effect.

![image](https://github.com/d4rkc0d3r/d4rkAvatarOptimizer/assets/41306347/26d206b0-e870-4ec2-b855-9436f3276972)

```
Shader error in 'd4rkpl4y3r/Optimizer/M_Hair Poiyomi Toon': undeclared identifier '_MatcapPan' at Packages/d4rkpl4y3r.d4rkavataroptimizer/TrashBin/ZZZ3def52bcba776384b1f68b2b95d67a5a.cginc(3717) (on d3d11)
```
![image](https://github.com/d4rkc0d3r/d4rkAvatarOptimizer/assets/41306347/26c350ea-a6ec-44c8-bb01-4f5b7dcd1608)

**Comment by d4rkc0d3r** [comment]
I talked to poi about it and it will be fixed in a future poi version.
It also causes the lock in to be pink when having no matcap texture but the pan is marked as animated.

**Comment by d4rkc0d3r** [comment]
Poi 9.0.42 is out and has it fixed.
