### ISSUE TITLE
NaNimation is causing wrong materials 

### ISSUE THREAD

**Issue by jerryzmtz** [d4rkc0d3r/d4rkAvatarOptimizer#82]
I have encountered two issues that does not exist before optimizer 3.5.0

Environment: 
VRCSDK 3.5.1
d4rkAvatarOptimizer 3.5.0
VRCFury 1.795.0
NDMF 1.3.6
poiyomi 8.1.167
liltoon 1.7.2

To reproduce 

1. NaNimation is causing some the meshes to be pure black when I use poiyomi and liltoon at the same time. I have made animations to change the min brightness of poiyomi and liltoon materials, but it should be no way to make liltoon materials to be pure black like this. I don't know how to specify the exact issue. This issue will not occur if only I cancel NaNimation.
![Screenshot_10](https://github.com/d4rkc0d3r/d4rkAvatarOptimizer/assets/26083118/3301bce7-a74c-45d0-bf81-8aed4c47fefd)
![Screenshot_8](https://github.com/d4rkc0d3r/d4rkAvatarOptimizer/assets/26083118/1350aee1-cda3-4120-9103-9e0f6ccdea98)
Without NaNimation: ![Screenshot_6](https://github.com/d4rkc0d3r/d4rkAvatarOptimizer/assets/26083118/a137ce8a-0e72-41da-bdf8-16dfa75d4419)

2. FaceTracking seems to break after optimizations. This does not happen if I test avatars in play mode (NDMF+VRCFury executed) or baked avatars (NDMF bake avatar+VRCFury build test avatars) without d4rkoptimizer.
![Screenshot_9](https://github.com/d4rkc0d3r/d4rkAvatarOptimizer/assets/26083118/503bad98-49a6-4175-860c-74cc30dad53b)
Without optimizations: ![Screenshot_7](https://github.com/d4rkc0d3r/d4rkAvatarOptimizer/assets/26083118/db652ab5-fdce-4fb7-819b-2da26924ec58)

[TrashBin.zip](https://github.com/d4rkc0d3r/d4rkAvatarOptimizer/files/14443173/TrashBin.zip)
[VF_Sotai_Chiffon_max_11bits_Clone__Clone_.zip](https://github.com/d4rkc0d3r/d4rkAvatarOptimizer/files/14443178/VF_Sotai_Chiffon_max_11bits_Clone__Clone_.zip)

**Comment by d4rkc0d3r** [comment]
Ok, for face tracking I have an idea what causes it. Seems like it is animating Animator parameters in there and the way I check if bindings are animatable doesn't find that so it deletes all of that. Should be easy to fix...

For the other issue I would like some additional info from you:
1. What material/shader are the socks?
2. What material/shader is in the first slot of the same mesh as the socks after merging.
3. Screenshot of the list of materials in the merged mesh that include the socks.
4. Screenshot of the merge preview around the socks mesh/material after baking NDMF/VRCFury but before optimizer runs.

**Comment by d4rkc0d3r** [comment]
Try 3.5.1 to see if it fixes the face tracking.

**Comment by jerryzmtz** [comment]
By the way, I could bake NDMF dependently but could not separte VF bake and d44k optimizations. When I bake VF, d4rk is triggered.

1. The material of the socks is liltoon.
![image](https://github.com/d4rkc0d3r/d4rkAvatarOptimizer/assets/26083118/b4e24fb6-7263-451a-82fa-33b23c91d657)
2. The first slot of the same mesh where socks belong to is poiyomi. 
![image](https://github.com/d4rkc0d3r/d4rkAvatarOptimizer/assets/26083118/e39d69eb-3a41-403a-b0ec-a68a5b55f916)
![image](https://github.com/d4rkc0d3r/d4rkAvatarOptimizer/assets/26083118/33dab7bc-7182-4f5e-8f6c-bcf777ab4b94)
3. Screenshot of the list of materials in the merged mesh that include the socks.
![image](https://github.com/d4rkc0d3r/d4rkAvatarOptimizer/assets/26083118/8b21672d-9f99-43bd-9ff3-b109adb71313)
4. Screenshot of the merge preview around the socks mesh/material after baking NDMF/VRCFury but before optimizer runs.
![image](https://github.com/d4rkc0d3r/d4rkAvatarOptimizer/assets/26083118/18f6641c-f3ac-4d12-857f-945901583082)

**Comment by jerryzmtz** [comment]
> Try 3.5.1 to see if it fixes the face tracking.

FaceTracking is all right in Unity. Thx

**Comment by d4rkc0d3r** [comment]
> 1. I could bake NDMF dependently but could not separate VF bake and d44k optimizations. When I bake VF, d4rk is triggered. It seems that sometimes d4rk could be triggered respectively, sometimes not, I could not understand the rule. When I open the issue, I could separate VF and d4rk, but I could not do it now.

Simply uncheck the `Optimize on Upload` checkbox on the optimizer and I think fury will not run my optimizer when building the test avatar.

> 2. Only when I enter play mode, will the socks become pure black. So probably the lightness is animated. But I have never animated liltoon to be black.  I do animate the lowest lightness of liltoon and the multiplier of the lightness of poiyomi.

Yes, once again I suspect some weirdness of WD ON material property animations. Here the problem seems to be that the first material of the merged mesh is poi while the socks get merged in later and are lilToon. If the poi material doesn't have the property you animate for the socks, then its default value will be 0 instead of what is set on the socks initially. But I need to investigate that a bit further to verify that.

Thanks for all the info so far!

**Comment by jerryzmtz** [comment]
> > 1. I could bake NDMF dependently but could not separate VF bake and d44k optimizations. When I bake VF, d4rk is triggered. It seems that sometimes d4rk could be triggered respectively, sometimes not, I could not understand the rule. When I open the issue, I could separate VF and d4rk, but I could not do it now.
> 
> Simply uncheck the `Optimize on Upload` checkbox on the optimizer and I think fury will not run my optimizer when building the test avatar.
> 
> > 2. Only when I enter play mode, will the socks become pure black. So probably the lightness is animated. But I have never animated liltoon to be black.  I do animate the lowest lightness of liltoon and the multiplier of the lightness of poiyomi.
> 
> Yes, once again I suspect some weirdness of WD ON material property animations. Here the problem seems to be that the first material of the merged mesh is poi while the socks get merged in later and are lilToon. If the poi material doesn't have the property you animate for the socks, then its default value will be 0 instead of what is set on the socks initially. But I need to investigate that a bit further to verify that.
> 
> Thanks for all the info so far!

Thx for your instructions. And here is a probably related issue:

1. Emission of face (the green material) is animated to none after optimizations in play mode. The optimized copy in editor or NDMF/VF baked copy of the original avatar looks good.
![image](https://github.com/d4rkc0d3r/d4rkAvatarOptimizer/assets/26083118/97e274bc-1a05-464b-b54c-2e2ca6c26c6f)
![Screenshot_6](https://github.com/d4rkc0d3r/d4rkAvatarOptimizer/assets/26083118/a3a9ecc1-1433-4b6e-920d-2ce380f5cc44)
![Screenshot_7](https://github.com/d4rkc0d3r/d4rkAvatarOptimizer/assets/26083118/87f7d385-3eed-4e02-aa95-d34206b2297e)

The face has two materials:

1. Poi transparent material without emission session (Red). Appears as the first material in combined mesh.
2. Poi opaque material with emission session(Green)

I tried to fix this by enabling the red material's emission sessions, but it does not help. I also have tried to enable the emission session of the Shoes' material (VRCFury Material for shoes_lime Poiyomi Toon Outline), which also appears to be the first material of the combined mesh , it did not help either.

**Comment by jerryzmtz** [comment]
I doubt this is a new issue since v3.5.0: `Reduced generated shader complexity handling material property animations`. As I am keeping met issues with material property animations applied for poiyomi like `_RimEnviroIntensity`, `_EmissionStrength`. which is not a problem in the previous version. And this is probably triggered when the merged mesh has poiyomi shaders and other shaders together

**Comment by d4rkc0d3r** [comment]
I changed how material property animations are handled with WD ON.
As such I will close this as its no longer relevant to what the optimize is doing now.
Please make new bug reports if issues arise.
