### ISSUE TITLE
GoGo Loco beyond prefab flight station is left default on due to d4

### ISSUE THREAD

**Issue by Zexxx** [d4rkc0d3r/d4rkAvatarOptimizer#83]
A destructive change in 3.5.X(0, 1, 2) has caused the GoGo Loco beyond prefab's station used for avatar flight to become a clickable station for remote users. Exclusions does not solve the issue. 
I'm using VRCFury to install GoGo Loco.
![image](https://github.com/d4rkc0d3r/d4rkAvatarOptimizer/assets/21136842/a19084aa-8046-4bda-88fa-633696bebe2c)

**Comment by d4rkc0d3r** [comment]
Does it happen when `Optimize FX Layer` is disabled?

Please send the original animations that animate stuff on the affected object and a zip of `Packages/d4rkAvatarOptimizer/TrashBin` after the optimizer ran.

**Comment by dtupper** [comment]
+1, also experiencing this. Turning off Optimize FX Layer does not fix it.

**Comment by d4rkc0d3r** [comment]
This happened because the prefab doesn't have a BoxCollider but animates it. The VRCStation will add a BoxCollider at runtime but my optimizer didn't knew that will happen so it thought those animations were useless.
