### ISSUE TITLE
Transform issues with particles 3.5.3

### ISSUE THREAD

**Issue by jerryzmtz** [d4rkc0d3r/d4rkAvatarOptimizer#91]
I noticed that particle system works strange with 3.5.3, and work good in 3.4.1.

For example, Particle trails become scaled up and rotated after optimizations. Another issue is that particles triggered by sphere collider seem to not exist anymore after optimizations.

Have not got enough time to specify the issues and explain the whole process, so I would like to post here to see anyone else have similar issues.

**Comment by d4rkc0d3r** [comment]
I have reproduced this issue. It stops happening with delete unused components turned off.

**Comment by d4rkc0d3r** [comment]
The VF_whitebreath bug is fixed since 3.6.1. If there are still other things broken please make a new bug report with info on that.
