### ISSUE TITLE
"Delete unused GameObjects" option can break Play Audio State Behaviour

### ISSUE THREAD

**Issue by TheMrGong** [d4rkc0d3r/d4rkAvatarOptimizer#93]
Source path needs to be updated to the moved position

**Comment by d4rkc0d3r** [comment]
Adding the audio source to the exclusion list should work as a workaround until I fix this eventually.
The exclusion list also ensures that `Delete unused GameObjects` doesn't delete anything in the path of one of the excluded objects.

**Comment by d4rkc0d3r** [comment]
fixed in 3.6.1
