### ISSUE TITLE
avatar disappears after upload.

### ISSUE THREAD

**Issue by lillycakez** [d4rkc0d3r/d4rkAvatarOptimizer#96]
i used the optimizer and everything worked fine but the moment i hit upload everything disappeared and the avatar was invisible in game too. this has happened every time i use it.

**Comment by d4rkc0d3r** [comment]
Please describe what exactly you did by "i used the optimizer" and how you determined "everything worked fine".
Does it happen when you have the optimizer on the avatar but uncheck "Optimize on Upload"?

A screenshot of the settings used might help as well as any extra info you can find.

Further things you can try is to use the "Basic" preset if you didn't already as that one should work more reliably than the more advanced settings.

**Comment by d4rkc0d3r** [comment]
I'll close this as there is not enough info to do anything about it.
