### ISSUE TITLE
Multiple Issues with 2022.3.22f1

### ISSUE THREAD

**Issue by Toys0125** [d4rkc0d3r/d4rkAvatarOptimizer#99]
GGloco breaking only having the feet moving. #98 
Toggling Gameobject no longer works with NaNimation Toggles extra toggle "Keep Enabled States"

**Comment by d4rkc0d3r** [comment]
I can reproduce that `NaNimation Toggles` with `Keep Default Enabled State` does not correctly enable the disabled skinned mesh renderer with the animation in 2022.3.22f1
